# Generated by Django 3.0.3 on 2020-06-10 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Textz',
            fields=[
                ('text_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_favourite', models.IntegerField(default=0)),
                ('text_user', models.CharField(max_length=20)),
                ('text_date', models.DateField(default=datetime.datetime(2020, 6, 10, 13, 47, 9, 254842, tzinfo=utc))),
                ('text_head', models.CharField(max_length=20)),
                ('text_tt', models.TextField()),
                ('text_jianjie', models.TextField()),
            ],
        ),
    ]
